In [1]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
#selesaikan soal berikut
#what is the transpose of this vector ([[25],[2],[-3],[-23]])

In [4]:
#numpy
x = np.array([[25],[2],[-3],[-23]])
x = x.T
x

array([[ 25,   2,  -3, -23]])

In [5]:
#pytoch
x_pt = torch.tensor([[25],[2],[-3],[-23]])
x_pt = x_pt.T
x_pt

tensor([[ 25,   2,  -3, -23]])

In [6]:
#tensorflow
x_tf = tf.Variable([[25],[2],[-3],[-23]])
x_tf = tf.transpose(x_tf)
x_tf

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 25,   2,  -3, -23]], dtype=int32)>