In [1]:
import numpy as np

In [3]:
#1. buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[1,2,3],[7,8,9]])
x

array([[1, 2, 3],
       [7, 8, 9]])

In [4]:
#tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [7]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
x[:,0]

array([1, 7])

In [9]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
x[1:2]

array([[7, 8, 9]])

In [10]:
#2. ulangi soal nomor 1 menggunakan pytorch
import torch

In [12]:
#buat matrix X berukuran 2x3 menggunakan pytoch
x_pt = torch.tensor([[1,2,3],[7,8,9]])
x_pt

tensor([[1, 2, 3],
        [7, 8, 9]])

In [14]:
#tampilkan ukuran dari matrix X
x_pt.shape

torch.Size([2, 3])

In [16]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
x_pt[:,0]

tensor([1, 7])

In [17]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
x_pt[1:2]

tensor([[7, 8, 9]])

In [18]:
#ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [19]:
#buat matrix X berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[1,2,3],[7,8,9]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9]], dtype=int32)>

In [20]:
#tampilkan ukuran dari matrix X
x_tf.shape

TensorShape([2, 3])

In [21]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
x_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

In [23]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
x_tf[1:2]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[7, 8, 9]], dtype=int32)>