In [35]:
import numpy as np

In [3]:
#1. buat vector x dengan ukuran 3x1
x = np.array([32, 3, 2])
x

array([32,  3,  2])

In [4]:
#hitung panjang vector x
len(x)

3

In [5]:
#tampilkan ukuran vector x
x.shape

(3,)

In [6]:
# tampilkan tipe data dari vector x
type(x)


numpy.ndarray

In [7]:
#akses elemen pertama dari vector x
x[0]

np.int64(32)

In [8]:
#tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [9]:
#2.lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([32,  3,  2])

In [10]:
#tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [16]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[23, 2, 3]])

y_t =y.T
y_t

array([[23],
       [ 2],
       [ 3]])

In [18]:
#tampilkan ukuran dari vector x_y
y_t.shape

(3, 1)

In [19]:
# 3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [30]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
#pytoch
x_pt = torch.tensor([[32, 3, 2]])

x_t=x_pt.T
x_t



tensor([[32],
        [ 3],
        [ 2]])

In [33]:
#tampilkan ukuran dari vector x_t
x_t.shape

TensorShape([3, 1])

In [43]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y_pt = torch.tensor([[23, 2, 3]])

y_t=y_pt.T
y_t


tensor([[23],
        [ 2],
        [ 3]])

In [44]:
#tampilkan ukuran dari vector x_y
y_t.shape

torch.Size([3, 1])

In [45]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
#tensorflow

x_tf = tf.Variable([[32, 3, 2]])

x_t = tf.transpose(x_tf)
x_t

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[32],
       [ 3],
       [ 2]], dtype=int32)>

In [46]:
#tampilkan ukuran dari vector x_t
x_t.shape


TensorShape([3, 1])

In [50]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y_tf = tf.Variable([[23, 2, 3]])

y_t = tf.transpose(y_tf)
y_t


<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[23],
       [ 2],
       [ 3]], dtype=int32)>

In [51]:
#tampilkan ukuran dari vector x_y
y_t.shape

TensorShape([3, 1])